paginate: 33
paginate_path: "news/page:num/"

prose:
  media: "news/img"
  metadata:
    _posts:
      - name: "type"
        field:
          element: "select"
          label: "Post type"
          help: "Select a post type to set if a post should show up in the 'News' section or 'What's On' section."
          options:
            - name: "News Post"
              value: "news"
            - name: "What's New Item"
              value: "current"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "title"
        field:
          element: "text"
          label: "title"
