function displayClassesPreview(data)
{
    var today = new Date();
    var classes = [];

    for (var i = 0; i < data.classes.length; i++)
    {
        for (var j = 0; j < data.classes[i].dates.length; j++)
        {
            var date2 = new Date(data.classes[i].dates[j][0]);
                    
            if (date2 >= today)
            {
                var currentClass = data.classes[i];
                for (var k = 0; k < currentClass.dates[j].length; k++) { var x = currentClass.dates[j][k]; currentClass.dates[j][k] = x.substring(0, x.length - 5); }
                classes.push({ "title" : currentClass.title, "date" : currentClass.dates[j], "time" : currentClass.times[j], "epoch" : date2.getTime(), "image" : currentClass.image});
            }
        }
    }
    classes.sort( function(a, b) { return a.epoch - b.epoch; } );
    
    var child = document.createElement('div');
    if (classes.length == 0)
    {
        $("#noclasses").show();
    }
    else
    {
        var obj = { "array" : classes };
        child.innerHTML = doTClasses( obj );
        child = child.firstChild;
        document.getElementById('insertClasses').appendChild(child); 
    }
}


function displayClassesPage(data)
{
    var today = new Date();
    $("#noclasses").show();

    for (var i = 0; i < data.classes.length; i++)
    {
        var valid = false;

        for (var j = 0; j < data.classes[i].dates.length; j++)
        {
            var date2 = new Date(data.classes[i].dates[j][0]);
                    
            if (date2 >= today)
            {
                valid = true;
            }
        }
       
        if (valid)
        {
            $("#noclasses").hide();
            var child = document.createElement('div');
            child.innerHTML = doTSummary(data.classes[i]);
            child = child.firstChild;
            document.getElementById('insertClasses').appendChild(child); 
        }
    }
    
}


function loadClasses(onLoad)
{
    var request = new XMLHttpRequest();
    if (onLoad == displayClassesPage)
        request.open("GET", "https://api.github.com/repos/woolandsilkco/woolandsilkco.github.io/contents/classes/classesmin.json", true);
    else
        request.open("GET", "https://api.github.com/repos/woolandsilkco/woolandsilkco.github.io/contents/classes/classespreviewmin.json", true);

    request.onload = function()
    {
        $("#loading").hide();
        onLoad(JSON.parse(atob(JSON.parse(request.response).content.replace(/\s/g, ''))));
    }

    request.onerror = function()
    {
        $("#loading").hide();
        $("#error").show();
    }

    request.send();
}


/* doT.js template code generated by the following template:
 *  <span>{{~it.array :value:index}}<p>{{? value.img}}<img src={{=value.img}} alt="">{{?}}<span class="title">{{=value.title}}</span> - {{~value.date :value2:index2}}{{? index2 > 0}} & {{?}}{{=value2}}{{~}}<span class="time">({{=value.time}})</span></p>{{~}}</span>
 */
function doTClasses(it) { var out='<span>';var arr1=it.array;if(arr1){var value,index=-1,l1=arr1.length-1;while(index<l1){value=arr1[index+=1];out+='<p>';if(value.img){out+='<img src='+(value.img)+' alt="">';}out+='<span class="title">'+(value.title)+'</span> - ';var arr2=value.date;if(arr2){var value2,index2=-1,l2=arr2.length-1;while(index2<l2){value2=arr2[index2+=1];if(index2 > 0){out+=' & ';}out+=''+(value2);} } out+='<span class="time">('+(value.time)+')</span></p>';} } out+='</span>';return out; }


/* doT.js template code generated by the following template:
    <article class="narrow">
        <h1>{{=value.title}}{{? value.parts > 1}} - {{=value.parts}} Parts{{?}} <span>{{=value.cost}}</span></h1>
        <div class="classbox content clearfix">
            {{? value.img}}<img src={{=value.img}} alt="">{{?}}
            {{? value.note}}<h3>Note: {{=value.note}}</h3>{{?}}
            <h4>Dates</h4>
            <p>{{~value.dates :value2:index2}}{{? index2 > 0}}  OR  {{?}}{{~value2 :value3:index3}}{{? index3 > 0}} & {{?}}{{=value3}}{{~}}{{~}}</p>
            <h4>Times</h4>
            <p>{{~value.times :value2:index2}}{{? index2 > 0}} OR {{?}}{{=value2}}{{~}}</p>
            <h4>Description</h4>
            <p>{{=value.description}}</p>
            <h4>Prerequisites</h4>
            <p>{{=value.prerequisites}}</p>
            <h4>Supplies</h4>
            <p>{{=value.supplies}}</p>
        </div>
    </article>
*/
function doTSummary(it) { var out='<article class="narrow"><h1>'+(value.title);if(value.parts > 1){out+=' - '+(value.parts)+' Parts';}out+=' <span>'+(value.cost)+'</span></h1><div class="classbox content clearfix"> ';if(value.img){out+='<img src='+(value.img)+' alt="">';}out+=' ';if(value.note){out+='<h3>Note: '+(value.note)+'</h3>';}out+=' <h4>Dates</h4> <p>';var arr1=value.dates;if(arr1){var value2,index2=-1,l1=arr1.length-1;while(index2<l1){value2=arr1[index2+=1];if(index2 > 0){out+=' OR ';}var arr2=value2;if(arr2){var value3,index3=-1,l2=arr2.length-1;while(index3<l2){value3=arr2[index3+=1];if(index3 > 0){out+=' & ';}out+=''+(value3);} } } } out+='</p> <h4>Times</h4> <p>';var arr3=value.times;if(arr3){var value2,index2=-1,l3=arr3.length-1;while(index2<l3){value2=arr3[index2+=1];if(index2 > 0){out+=' OR ';}out+=''+(value2);} } out+='</p> <h4>Description</h4> <p>'+(value.description)+'</p> <h4>Prerequisites</h4> <p>'+(value.prerequisites)+'</p> <h4>Supplies</h4> <p>'+(value.supplies)+'</p> </div> </article>';return out; }

